config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, :picture_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="mx-3">
  <div class="row">
    <div class="col-12">
      <h1>Our lovely flats (<%= @flats.count %>)</h1>
    </div>
  </div>


  <div class="card-grid">
    <% @flats.each do |flat| %>
      <div class="card" style="width: 18rem;">
        <div class="card-content">
          <img class="card-img-top" src='<%= flat.picture_url %>' alt="Card image cap">

          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"> <%= flat.address %> </p>
            <p class="card-text-bottom"> <i class="fas fa-users"></i> <%= flat.number_of_guests %> <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %> </p>
          </div>
        </div>
        <div class="card-footer bg-white">
          <%= link_to 'More info', flat_path(flat), class:"btn btn-link"%>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for (@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.input :picture_url %>
  <%= f.submit "Add flat", class: "btn btn-info" %>
<% end %>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url(' <%= @flat.picture_url %>');">
</div>

<div class="container margin-top-negative">
  <div class="flat-details">

    <div class="flat-box">
      <h2><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
    </div>

    <div class="flat-box">
      <h4>A bit more about this flat..</h4>
      <p> <%= @flat.description %> </p>
      <div class="map" style="background-image: url('https://images.squarespace-cdn.com/content/v1/524883b7e4b03fcb7c64e24c/1443035740954-0KYX5313WPOAVCH44RIQ/ke17ZwdGBToddI8pDm48kKhztsF-0Z40vB295VWXIkwUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYy7Mythp_T-mtop-vrsUOmeInPi9iDjx9w8K4ZfjXt2duxdlE-YIor3Gsw6mueOp4Ecthq2xyBEFG5UZv2GVS1aCjLISwBs8eEdxAxTptZAUg/image-asset.png')">
      </div>

    </div>

    <div class="flat-box">
      <h4>Details</h4>
      <p> <i class="fas fa-users"></i> <%= @flat.number_of_guests %> <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %> </p>
    </div>

  </div>

  <div class="flat-book">

    <div class="flat-box">
      <h2>Book it!</h2>

      <div class="col-auto p-0">
        <label class=“sr-only” for="inlineFormInputGroup"></label>
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <div class="input-group-text">From:</div>
          </div>
          <input type="date" class="form-control" id="inlineFormInputGroup" placeholder="12/10/2017">
        </div>

        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <div class="input-group-text">To:</div>
          </div>
          <input type="date" class="form-control" id="inlineFormInputGroup" placeholder="12/10/2017">
        </div>
      </div>

      <button type="button" class="btn btn-success" style="width: 100%">Book now</button>

    </div>

    <div class="flat-box">
      <h5>Share</h5>
      <i class="fab fa-facebook-square"></i>
      <i class="fab fa-twitter-square"></i>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-light bg-light">
      <h4><%= link_to "Simple AirBnb", flats_path %></h4>
      <button type="button" class="btn btn-outline-primary"><%= link_to "Add a flat", new_flat_path %></button>
    </nav>

    <%= yield %>

  </body>
</html>